#pragma config(StandardModel, "RANGER")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*--------------------------------------------------------------------------------------------------------*\
|*                                                                                                        *|
|*                                   - Obstacle Detection with Sonar -                                    *|
|*                                            ROBOTC on NXT                                               *|
|*                                                                                                        *|
|*  This program runs your robot forward until it detects and obstacle, at which point it stops.          *|
|*                                                                                                        *|
|*                                        ROBOT CONFIGURATION                                             *|
|*    NOTES:                                                                                              *|
|*    1)  The Sonar Sensor should be somewhere on the FRONT of the robot, facing FORWARD.                 *|
|*                                                                                                        *|
|*    MOTORS & SENSORS:                                                                                   *|
|*    [I/O Port]              [Name]              [Type]              [Description]                       *|
|*    Port B                  motorB              NXT                 Right motor                         *|
|*    Port C                  motorC              NXT                 Left motor                          *|
|*    Port 4                  sonarSensor         Sonar Sensor        Front mounted, front facing         *|
\*---------------------------------------------------------------------------------------------------4246-*/


task main()
{
  int distance_in_cm = 50;   // Create variable 'distance_in_cm' and initialize it to 20(cm).
	for (int i=0; i<4; i++)
	{
  	 	while(SensorValue[S4] > distance_in_cm)   // While the Sonar Sensor readings are less than the specified, 'distance_in_cm':
   		{
      		motor[motorD] = 50;                     // Motor B is run at a 75 power level
      		motor[motorE] = 50;
   		}
   		motor[motorD] = 0;
   		motor[motorE] = 0;
   		wait1Msec(500);

   		motor[motorD] = 25;
   		motor[motorE] = -25;
   		wait1Msec(900);
 }
}
