#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     irSensor,       sensorHiTechnicIRSeeker600)
#pragma config(Motor,  mtr_S1_C1_1,     rightDrive,    tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     leftDrive,     tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     arm,           tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     gHook,         tmotorTetrix, openLoop)
#pragma config(Motor,  motorA,    gripper,              tServoStandard)
#pragma config(Servo,  srvo_S1_C3_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// This is for the NXT model, not TETRIX

/************************************\
|*  Robot Virtual World Template    *|
|*                                  *|
|*  DO NOT OVERWRITE THIS FILE      *|
|*  MAKE SURE TO "SAVE AS" INSTEAD  *|
\************************************/

int driveSpeed = 50;

task main()
{
	 	motor[rightDrive] = driveSpeed;
		motor[leftDrive] = driveSpeed;

		wait10Msec(100);

		motor[rightDrive] = driveSpeed;
		motor[leftDrive] = -driveSpeed;

		wait10Msec(72);

		motor[rightDrive] = driveSpeed - 8;
		motor[leftDrive] = driveSpeed - 8;

		wait1Msec(1600);

		motor[arm] = driveSpeed;
		motor[rightDrive] = 0;
		motor[leftDrive] = 0;

		wait1Msec(650);

		motor[arm] = 0;
		motor[rightDrive] = driveSpeed;
		motor[leftDrive] = driveSpeed;

		wait1Msec(950);

		motor[rightDrive] = 0;
		motor[leftDrive] = 0;
		motor[gripper] = -50;

		wait1Msec(200);

		motor[rightDrive] = -driveSpeed;
		motor[leftDrive] = -driveSpeed;

		wait1Msec(1200);

		motor[rightDrive] = 0;
		motor[leftDrive] = 0;

		wait1Msec(300);

		motor[rightDrive] = -driveSpeed;
		motor[leftDrive] = driveSpeed;

		wait1Msec(1000);

		motor[rightDrive] = 0;
		motor[leftDrive] = 0;

		wait1Msec(200);

		motor[rightDrive] = driveSpeed;
		motor[leftDrive] = driveSpeed;

		wait1Msec(2200);

		motor[rightDrive] = driveSpeed;
		motor[leftDrive] = -driveSpeed;

		wait1Msec(1000);

		motor[rightDrive] = driveSpeed + 25;
		motor[leftDrive] = driveSpeed + 25;

		wait1Msec(2000);

		motor[rightDrive] = 0;
		motor[leftDrive] = 0;

		while(true){}

}
