#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Hubs,  S3, HTServo,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     irSensor,       sensorHiTechnicIRSeeker600)
#pragma config(Sensor, S3,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     rightDrive,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     leftDrive,     tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     arm,           tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     gHook,         tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S3_C1_1,    gripper,              tServoStandard)
#pragma config(Servo,  srvo_S3_C1_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S3_C1_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S3_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S3_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S3_C1_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//



task main()
	{
	int counter = 0;
	motor[rightDrive] = 75;
	motor[leftDrive] = 0;
	wait1Msec(1000);
	motor[rightDrive] = 0;
	motor[leftDrive] = 0;

	motor[rightDrive] = 75;
	motor[leftDrive] = 75;
	wait1Msec(500);
	motor[rightDrive] = 0;
	motor[leftDrive] = 0;

	motor[rightDrive] = 75;
	motor[leftDrive] = 0;
	wait1Msec(750);
	motor[rightDrive] = 0;
	motor[leftDrive] = 0;

	motor[rightDrive] = 75;
	motor[leftDrive] = 75;
	wait1Msec(1000);
	motor[rightDrive] = 0;
	motor[leftDrive] = 0;

	motor[rightDrive] = 0;
	motor[leftDrive] = 75;
	wait1Msec(770);
	motor[rightDrive] = 0;
	motor[leftDrive] = 0;


	while(SensorValue[IRSeeker] != 8)
		{
		motor[rightDrive] = 100;
		motor[leftDrive] = 100;
		wait1Msec(1);
		counter++;
		}
		motor[rightDrive] = 100;
		motor[leftDrive] = 100;
		wait1Msec(900);
		motor[rightDrive] = 0;
		motor[leftDrive] = 0;
		// dropping off the block
		motor[arm] = 30;
		wait1Msec(2000);
		motor[arm] = 0;

		motor[rightDrive] = -75;
		motor[leftDrive] = 75;
		wait1Msec(1000);
		motor[rightDrive] = 0;
		motor[leftDrive] = 0;

		motor[arm] = 30;
		wait1Msec(100);
		motor[arm] = 0;
		servoTarget[gripper] = 100;
		wait1Msec(100);
		// getting back

		motor[arm] = -30;
		wait1Msec(100);
		motor[arm] = 0;

		motor[rightDrive] = 75;
		motor[leftDrive] = -75;
		wait1Msec(970);
		motor[rightDrive] = 0;
		motor[leftDrive] = 0;

		motor[arm] = 30;
		wait1Msec(1500);
		motor[arm] = 0;

		motor[rightDrive] = -100;
		motor[leftDrive] = -100;
		wait1Msec(2000+counter);
		motor[rightDrive] = 0;
		motor[leftDrive] = 0;
		// getting on the ramp
		motor[rightDrive] = -75;
		motor[leftDrive] = 75;
		wait1Msec(1000);
		motor[rightDrive] = 0;
		motor[leftDrive] = 0;

		motor[rightDrive] = 100;
		motor[leftDrive] = 100;
		wait1Msec(2000);
		motor[rightDrive] = 0;
		motor[leftDrive] = 0;

		motor[rightDrive] = 75;
		motor[leftDrive] = -75;
		wait1Msec(1000);
		motor[rightDrive] = 0;
		motor[leftDrive] = 0;

		motor[rightDrive] = 75;
		motor[leftDrive] = 75;
		wait1Msec(3000);
		motor[rightDrive] = 0;
		motor[leftDrive] = 0;
	}
