#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     irSensor,       sensorHiTechnicIRSeeker1200)
#pragma config(Motor,  mtr_S1_C1_1,     leftDrive,     tmotorTetrix, PIDControl, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     rightDrive,    tmotorTetrix, PIDControl)
#pragma config(Motor,  mtr_S1_C2_1,     arm,           tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     gHook,         tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C3_1,    gripper,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

task display()
{

    while (true)
    {
			int display = SensorValue[irSensor];
			int right = nMotorEncoder[rightDrive];
			int left = nMotorEncoder[leftDrive];

			nxtDisplayString(0,"%d",display);
			nxtDisplayString(1, "Right: %d                      ", right);
			nxtDisplayString(2, "Left: %d                       ", left);
			wait10Msec(10);
	  }
}

void waitForStop()
{
	while(nMotorRunState[rightDrive] != runStateIdle && nMotorRunState[leftDrive] != runStateIdle)
	{
	}

	motor[leftDrive] = 0;
	motor[rightDrive] = 0;


}

void leftTurn()
{
	nMotorEncoder[rightDrive] = 0;
	nMotorEncoder[leftDrive] = 0;

	nMotorEncoderTarget[rightDrive] = 2200;
	nMotorEncoderTarget[leftDrive] = -2200;

	motor[rightDrive] = 30;
	motor[leftDrive] = -30;

	waitForStop();

	nMotorEncoder[rightDrive] = 0;
	nMotorEncoder[leftDrive] = 0;

}

void rightTurn()
{
	nMotorEncoder[rightDrive] = 0;
	nMotorEncoder[leftDrive] = 0;

	nMotorEncoderTarget[rightDrive] = -2200;
	nMotorEncoderTarget[leftDrive] = 2200;

	motor[rightDrive] = -30;
	motor[leftDrive] = 30;

	waitForStop();

	nMotorEncoder[rightDrive] = 0;
	nMotorEncoder[leftDrive] = 0;

}
void drive(int distanceRight, int distanceLeft,int speed, bool forward)
{
	nMotorEncoder[rightDrive] = 0;
	nMotorEncoder[leftDrive] = 0;

	nMotorEncoderTarget[rightDrive] = distanceRight;
	nMotorEncoderTarget[leftDrive] = distanceLeft;

	if(forward)
	{
		motor[rightDrive] = speed;
		motor[leftDrive] = speed;
	}
	else
	{
		motor[rightDrive] = -speed;
		motor[leftDrive] = -speed;
	}

	waitForStop();

	nMotorEncoder[rightDrive] = 0;
	nMotorEncoder[leftDrive] = 0;
}


task main()
{
	//waitForStart();
	servo[gripper] = 85;
	wait1Msec(100);
	StartTask(display);

	motor[arm] = -30;
	wait1Msec(1750);
	motor[arm] = 0;

	nMotorEncoder[leftDrive] = 0;
	nMotorEncoder[rightDrive] = 0;

	int distanceForwardRight = 0;
	int distanceForwardLeft = 0;

	// turning when IR is 2 and 8(?)
	while(SensorValue[irSensor] != 2)
	{
		motor[rightDrive] = 50;
		motor[leftDrive] = 50;
	}

	distanceForwardRight = nMotorEncoder[rightDrive];
	distanceForwardLeft = nMotorEncoder[leftDrive];

	drive(1400, 1400, 50, true);

	motor[rightDrive] = 0;
	motor[leftDrive] = 0;

	leftTurn();
	wait1Msec(300);
	drive(1700, 1700,40, true);
	wait1Msec(300);
	servo[gripper] = 240;
	wait1Msec(300);
	drive(-1700, -1700,30, false);
	wait1Msec(300);
	leftTurn();
	drive(distanceForwardRight + 1200, distanceForwardLeft + 1200, 60, true);
	wait1Msec(300);
	rightTurn();

}
