#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S2,     irSensor,       sensorHiTechnicIRSeeker600)
#pragma config(Motor,  mtr_S1_C1_1,     rightDrive,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     leftDrive,     tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     arm,           tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     gHook,         tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C3_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
task main()
	{
	bool forward = true;
	while(true)
		{
		if(nNxtButtonPressed == 3 && forward == true)
			forward = false;
		if(nNxtButtonPressed == 3 && forward == false)
			forward = true;

		if(forward) // if the arm is in the forward position
			{
			if(nNxtButtonPressed == 2) // down
				motor[arm] = 5;
			else if(nNxtButtonPressed == 1) // up
				motor[arm] = -50;
	 		else
				motor[arm] = 0;
			}

			if(!forward) // if the arm is in the backward position
			{
			if(nNxtButtonPressed == 2) // up
				motor[arm] = 50;
			else if(nNxtButtonPressed == 1) // down
				motor[arm] = -5;
	 		else
				motor[arm] = 0;
			}
		}
	}
