#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     irSensor,       sensorHiTechnicIRSeeker1200)
#pragma config(Sensor, S3,     sonar,          sensorSONAR)
#pragma config(Motor,  mtr_S1_C1_1,     leftDrive,     tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     rightDrive,    tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     arm,           tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     gHook,         tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C3_1,    gripper,              tServoNone)
#pragma config(Servo,  srvo_S1_C3_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"
#include "Autonomous Functions.h"

const bool competition = false;

task main()
{
	if(competition)
		waitForStart();

	servo[gripper] = 85;
	wait1Msec(100);
	StartTask(display);
	StartTask(armRaise);

	nMotorEncoder[leftDrive] = 0;
	nMotorEncoder[rightDrive] = 0;

	int distanceForwardRight = 0;
	int distanceForwardLeft = 0;
	int turnDistanceRight = 0;
	int turnDistanceLeft = 0;

	// turning when IR is 2 and 8(?)
	drive(0, 0, 90, true);
	while(SensorValue[irSensor] != 2)
	{
	}
	motor[leftDrive] = 0;
	motor[rightDrive] = 0;
	wait1Msec(200);
	distanceForwardRight = nMotorEncoder[rightDrive];
	distanceForwardLeft = nMotorEncoder[leftDrive];

	if(distanceForwardRight < 5000)
	{
		drive(1200, 1200, 90, false);
	}
	else
	{
		drive(400, 400, 90, false);
	}

	motor[rightDrive] = 0;
	motor[leftDrive] = 0;
	wait1Msec(250);

	Turn(-90);

	motor[rightDrive] = 50;
	motor[leftDrive] = 50;

	while(SensorValue[sonar] > 25)
	{
	}
	motor[rightDrive] = 0;
	motor[leftDrive] = 0;
	turnDistanceRight = nMotorEncoder[rightDrive] - 300;
	turnDistanceLeft = nMotorEncoder[leftDrive] - 300;
	wait10Msec(100);
	servo[gripper] = 240;
	wait1Msec(300);
	drive(-turnDistanceRight-500, -turnDistanceLeft-500, -90, false);
	Turn(-90);
	drive(distanceForwardRight + 800, distanceForwardLeft + 800, 90, false);
	Turn(70);
	drive(6000, 6000, 90, false);
	Turn(110);
	drive(6800, 6800, 90, false);
}
