#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     irSensor,       sensorHiTechnicIRSeeker1200)
#pragma config(Sensor, S3,     sonar,          sensorSONAR)
#pragma config(Motor,  mtr_S1_C1_1,     leftDrive,     tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     rightDrive,    tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     arm,           tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     gHook,         tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C3_1,    gripper,              tServoNone)
#pragma config(Servo,  srvo_S1_C3_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"
#include "Autonomous Functions.h"

const bool competition = false;

task main()
{
	if(competition)
		waitForStart();

	servo[gripper] = 85;
	StartTask(armRaise);
	wait1Msec(2000);
	while(SensorValue[sonar] > 30)
		{
		motor[rightDrive] = 60;
		motor[leftDrive] = 60;
		}
		motor[rightDrive] = 0;
		motor[leftDrive] = 0;

		drive(300, 300, 30, false);

		wait1Msec(500);
		servo[gripper] = 240;
		wait1Msec(200);
		drive(-1100, -1100, -90, false);
		wait1Msec(200);
		turn(90);
		wait1Msec(200);
		drive(4000, 4000, 90, false);
		wait1Msec(200);
		turn(-90);
		wait1Msec(200);
		drive(4500, 4500, 90, false);
	}
