#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     irSensor,       sensorHiTechnicIRSeeker1200)
#pragma config(Sensor, S3,     sonar,          sensorSONAR)
#pragma config(Motor,  mtr_S1_C1_1,     leftDrive,     tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     rightDrive,    tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     arm,           tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     gHook,         tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C3_1,    gripper,              tServoNone)
#pragma config(Servo,  srvo_S1_C3_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"
//OverlakeMat Right Turn encoderTicksPer10Degrees = 268

int encoderTicksPer10Degrees = 260;
const bool competition = false;

task display()
{
    while (true)
    {
			int display = encoderTicksPer10Degrees;
			nxtDisplayString(0,"%d",display);
	  }
}

void waitForStop()
{
	while(nMotorRunState[rightDrive] != runStateIdle && nMotorRunState[leftDrive] != runStateIdle)
	{
	}
	motor[leftDrive] = 0;
	motor[rightDrive] = 0;
}

void drive(int distanceRight, int distanceLeft, int speed)
{
	nMotorEncoder[rightDrive] = 0;
	nMotorEncoder[leftDrive] = 0;

	nMotorEncoderTarget[rightDrive] = distanceRight;
	nMotorEncoderTarget[leftDrive] = distanceLeft;

	motor[rightDrive] = speed;
	motor[leftDrive] = speed;

	waitForStop();

	nMotorEncoder[rightDrive] = 0;
	nMotorEncoder[leftDrive] = 0;
}

void Turn(int degrees)
{
	nMotorEncoder[rightDrive] = 0;
	nMotorEncoder[leftDrive] = 0;

	nMotorEncoderTarget[rightDrive] = -degrees*encoderTicksPer10Degrees / 10;
	nMotorEncoderTarget[leftDrive] = degrees*encoderTicksPer10Degrees / 10;

	if (degrees < 0)
	{
		motor[rightDrive] = 90;
		motor[leftDrive] = -90;
  }
  else
  {
		motor[rightDrive] = -90;
		motor[leftDrive] = 90;
  }

	waitForStop();

	nMotorEncoder[rightDrive] = 0;
	nMotorEncoder[leftDrive] = 0;
}

task main()
{
	StartTask(display);
	int pastButton = nNxtButtonPressed;
	while(true)
	{
		if(nNxtButtonPressed == 3)
		{
			wait1Msec(1000);
			drive(1400, 1400, 50);
			Turn(90);
			wait1Msec(500);
			drive(1400, 1400, 50);
			Turn(90);
			wait1Msec(500);
			drive(1400, 1400, 50);
			Turn(90);
			wait1Msec(500);
			drive(1400, 1400, 50);
			Turn(90);
		}

		if(nNxtButtonPressed != pastButton)
		{
			if(nNxtButtonPressed == 1 && pastButton != 1)
				encoderTicksPer10Degrees -= 1;
			if(nNxtButtonPressed == 2 && pastButton != 2)
				encoderTicksPer10Degrees += 1;
			pastButton = nNxtButtonPressed;
		}
	}
}
