#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     irSensor,       sensorHiTechnicIRSeeker600)
#pragma config(Motor,  motorA,          flag,          tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     rightDrive,    tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     leftDrive,     tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     arm,           tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     winch,         tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C3_1,    gripper,              tServoStandard)
#pragma config(Servo,  srvo_S1_C3_2,    safety,               tServoStandard)
#pragma config(Servo,  srvo_S1_C3_3,    trigger,              tServoStandard)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriverChanges.c"

#define BUTTON_X 1
#define BUTTON_Y 4
#define BUTTON_A 2
#define BUTTON_B 3
#define LEFT_BUTTON 5
#define RIGHT_BUTTON 6
#define START_BUTTON 10
#define TOP_HAT_UP 0
#define TOP_HAT_DOWN 4

int driveDamp = 25;

int leftMotorTarget = 0;
int rightMotorTarget = 0;
const int gripperOpenPos = 240;
const int gripperClosedPos = 85;
int rightJValue = 0;
int leftJValue = 0;

bool armTurbo = false;
bool armForward = false;
bool armBackward = false;
bool gripperOpen = false;


bool winchIn = false;

int targetPosition = 0;

const int position1Value = 1;
const int position2Value = 2600;
const int position3Value = 3900;
const int middleValue = 2800;

// min takes in two integers as paramaters and returns the smaller of the two
int min(int a, int b)
{
    return (a < b) ? a : b;
}

void initializeRobot()
{
    nMotorEncoder[leftDrive] = 0;
    nMotorEncoder[rightDrive] = 0;
    nMotorEncoder[arm] = 0;
    gripperOpen = false;
    return;
}

task display()
{
    while (true)
    {
        int display = nMotorEncoder[arm];

        nxtDisplayString(0,"arm: %d",display);
    }
}

/* inputManager reads input from both controllers and sets the values of
	 corresponding variables.

	 Controller 1:
	 		Left Joystick Y-Axis - Left Motor (leftMotorTarget)
	 		Right Joystick Y-Axis - Right Motor (rightMotorTarget)
	 		Left Button - Flag Raiser Counterclockwise
	 		Right Button - Flag Raiser Clockwise


	 	Controller 2:
	 		B - Opens or closes gripper (gripperOpen)
	 		DPad Up - Arm up (armForward)
	 		DPad Down - Arm down (armBackward)
	 		Left Button - Arm turbo (armTurbo)

*/
void inputManager()
{

    bool buttonBIsDown = false;
    bool buttonBWasDown = false;

    while(true)
    {
        getJoystickSettings(joystick);
        rightJValue =joystick.joy1_y2;
        leftJValue = joystick.joy1_y1;

        if(abs(joystick.joy1_y2) < 10)
        {
            leftMotorTarget = 0;
        }
        else
        {
            if(joystick.joy1_y2 > 0)
            {
                leftMotorTarget = ((long)(rightJValue*rightJValue)-100)*100/(128*128);
            }
            else
            {
                leftMotorTarget = -((long)(rightJValue*rightJValue)-100)*100/(128*128);
            }
        }

        if(abs(joystick.joy1_y1) < 10)
        {
            rightMotorTarget = 0;
        }
        else
        {
            if(joystick.joy1_y1 > 0)
            {
                rightMotorTarget = ((long)(leftJValue*leftJValue)-100)*100/(128*128);
            }
            else
            {
                rightMotorTarget = -((long)(leftJValue*leftJValue)-100)*100/(128*128);
            }
        }

        armTurbo = (joy2Btn(LEFT_BUTTON) == 1);

        armForward = (joystick.joy2_TopHat == TOP_HAT_UP);
        armBackward = (joystick.joy2_TopHat == TOP_HAT_DOWN);

        if((joy1Btn(RIGHT_BUTTON) == 1)&&(joy2Btn(RIGHT_BUTTON)==1))
        {
            winchIn=true;
        }
        else
        {
            winchIn = false;
        }

        buttonBIsDown = (joy2Btn(BUTTON_B) == 1);
        if(buttonBIsDown && !buttonBWasDown)
        {
            gripperOpen = !gripperOpen;
        }
        buttonBWasDown = buttonBIsDown;

        if (joy2Btn(START_BUTTON) == 1)
        {
            nMotorEncoder[arm] = 1;
        }

        if(joy2Btn(BUTTON_A) == 1)
        {
            targetPosition = position1Value;
        }
        else if(joy2Btn(BUTTON_X) == 1)
        {
            targetPosition = position2Value;
        }
        else if(joy2Btn(BUTTON_Y) == 1)
        {
            targetPosition = position3Value;
        }
        else if(armForward)
        {
            targetPosition = 20000;
        }
        else if(armBackward)
        {
            targetPosition = -20000;
        }
        else
        {
            motor[arm] = 0;
            targetPosition = 0;
        }
    }
}

// drive sets the values of the drive motors
task Drive()
{
    while(true)
    {
        if(motor[rightDrive] != rightMotorTarget)
        {
            if(motor[rightDrive] < rightMotorTarget)
            {
                motor[rightDrive] += min(driveDamp, rightMotorTarget - motor[rightDrive]);
            }
            else
            {
                motor[rightDrive] -= min(driveDamp, motor[rightDrive] - rightMotorTarget);
            }
        }

        if(motor[leftDrive] != leftMotorTarget)
        {
            if(motor[leftDrive] < leftMotorTarget)
            {
                motor[leftDrive] += min(driveDamp, leftMotorTarget - motor[leftDrive]);
            }
            else
            {
                motor[leftDrive] -= min(driveDamp, motor[leftDrive] - leftMotorTarget);
            }
        }

        wait10Msec(5);

    }
}

task ArmPositions()
{

    while(true)
    {
        bool forward = (nMotorEncoder[arm] < middleValue);

        if(targetPosition != 0)
        {
            if (abs(nMotorEncoder[arm] - targetPosition) > 100)
            {
                if(forward)
                {
                    if(nMotorEncoder[arm] > targetPosition)
                    {
                        if (!armTurbo)
                        {
                            motor[arm] = -4;
                        }
                        else
                        {
                            motor[arm] = -20;
                        }
                    }
                    else
                    {
                        if (!armTurbo)
                        {
                            motor[arm] = 70;
                        }
                        else
                        {
                            motor[arm] = 80;
                        }
                    }
                }
                else
                {
                    if(nMotorEncoder[arm] > targetPosition)
                    {
                        if (!armTurbo)
                        {
                            motor[arm] = -70;
                        }
                        else
                        {
                            motor[arm] = -80;
                        }
                    }
                    else
                    {
                        if (!armTurbo)
                        {
                            motor[arm] = 4;
                        }
                        else
                        {
                            motor[arm] = 20;
                        }
                    }
                }
            }
            else
            {
                motor[arm] = 0;
            }
        }
        else
        {
            motor[arm] = 0;
        }

    }
}

// gripper changes the servo value of the gripper
task Gripper()
{
    while(true)
    {
        if(!gripperOpen)
        {
            servo[gripper] = gripperClosedPos;
        }

        if(gripperOpen)
        {
            servo[gripper] = gripperOpenPos;
        }
    }
    wait10Msec(5);
}

task Winch()
{
    while(true)
    {
        if(winchIn)
        {
            motor[winch] = -85;
        }
        else
        {
            motor[winch] = 0;
        }

        wait10Msec(5);
    }
}

task main()
{
    initializeRobot();

    waitForStart();
    StartTask(Drive);
    StartTask(Gripper);
    StartTask(Winch);
    StartTask(ArmPositions);
    StartTask(display);
    inputManager();
}
